spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/edukeys
    username: edukeys
    password: edukeys
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
